-- Summit AI Training Platform - Initial Schema
-- This migration creates all core tables for the MVP

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- USERS TABLE
-- Managed by Supabase Auth, but we reference it
-- ============================================

-- ============================================
-- PROFILES TABLE
-- Stores user preferences and training context
-- ============================================
CREATE TABLE profiles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Core training info
  disciplines TEXT[] NOT NULL DEFAULT '{}',
  goal_text TEXT,
  goal_date DATE,
  hours_per_week INTEGER,
  days_per_week INTEGER,
  equipment TEXT[] DEFAULT '{}',

  -- Fitness baseline
  fitness_level TEXT CHECK (fitness_level IN ('beginner', 'intermediate', 'advanced', 'elite')),
  recent_activity TEXT,
  injuries TEXT,

  -- Terra integration (for watch sync)
  terra_user_id TEXT,
  terra_provider TEXT,

  -- Subscription status
  subscription_status TEXT DEFAULT 'trial' CHECK (subscription_status IN ('trial', 'active', 'canceled', 'past_due')),
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT,
  trial_ends_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '14 days'),

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  onboarding_completed_at TIMESTAMPTZ,

  UNIQUE(user_id)
);

-- ============================================
-- PLANS TABLE
-- Training plans generated by Claude
-- ============================================
CREATE TABLE plans (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Plan metadata
  name TEXT NOT NULL,
  discipline TEXT NOT NULL,
  goal TEXT NOT NULL,
  target_date DATE,

  -- Plan status
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'abandoned', 'paused')),

  -- The full plan structure as JSON
  -- Contains: weeks[], each with days[], each with workouts[]
  blocks JSONB NOT NULL,

  -- Duration
  duration_weeks INTEGER NOT NULL,
  current_week INTEGER DEFAULT 1,

  -- Training parameters
  weekly_hours INTEGER,
  periodization_type TEXT, -- 'linear', 'block', 'undulating'

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- ============================================
-- WORKOUTS TABLE
-- Individual workout sessions
-- ============================================
CREATE TABLE workouts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  plan_id UUID REFERENCES plans(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Scheduling
  scheduled_date DATE NOT NULL,
  week_number INTEGER,
  day_of_week INTEGER, -- 0 = Sunday, 6 = Saturday

  -- Workout details
  workout_type TEXT NOT NULL, -- 'strength', 'endurance', 'power', 'technique', 'recovery', 'rest'
  title TEXT NOT NULL,
  description TEXT,
  instructions JSONB, -- Detailed workout structure

  -- Targets
  planned_duration INTEGER, -- minutes
  target_intensity TEXT, -- 'easy', 'moderate', 'hard', 'max'
  target_zones JSONB, -- Heart rate zones, power zones, etc.

  -- Completion tracking
  completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  actual_duration INTEGER,
  rpe INTEGER CHECK (rpe >= 1 AND rpe <= 10), -- Rate of Perceived Exertion
  notes TEXT,

  -- Watch data (if synced)
  watch_data JSONB,

  -- Adaptation tracking
  was_adapted BOOLEAN DEFAULT FALSE,
  adaptation_reason TEXT,
  original_workout JSONB, -- Store original if adapted

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- METRICS TABLE
-- Data from wearables (via Terra)
-- ============================================
CREATE TABLE metrics (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Date for this metric snapshot
  date DATE NOT NULL,

  -- Recovery metrics
  hrv DECIMAL, -- Heart Rate Variability (ms)
  resting_hr INTEGER, -- Resting heart rate (bpm)
  sleep_score INTEGER, -- 0-100
  sleep_duration INTEGER, -- minutes
  sleep_efficiency DECIMAL, -- percentage

  -- Training load
  training_load INTEGER, -- Cumulative load score
  acute_load DECIMAL, -- 7-day average
  chronic_load DECIMAL, -- 28-day average
  load_ratio DECIMAL, -- Acute:Chronic ratio

  -- Readiness
  recovery_score INTEGER, -- 0-100
  strain_score DECIMAL, -- Whoop-style strain

  -- Activity
  steps INTEGER,
  active_calories INTEGER,

  -- Source
  source TEXT, -- 'garmin', 'apple', 'whoop', 'coros', 'manual'
  raw_data JSONB, -- Full payload from Terra

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(user_id, date)
);

-- ============================================
-- CHAT_HISTORY TABLE
-- Conversation history with the AI coach
-- ============================================
CREATE TABLE chat_history (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Message content
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,

  -- Context at time of message
  context_snapshot JSONB, -- What the AI knew when responding

  -- If this message resulted in plan changes
  plan_changes JSONB,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX idx_profiles_user_id ON profiles(user_id);
CREATE INDEX idx_plans_user_id ON plans(user_id);
CREATE INDEX idx_plans_status ON plans(status);
CREATE INDEX idx_workouts_user_id ON workouts(user_id);
CREATE INDEX idx_workouts_plan_id ON workouts(plan_id);
CREATE INDEX idx_workouts_scheduled_date ON workouts(scheduled_date);
CREATE INDEX idx_workouts_completed ON workouts(completed);
CREATE INDEX idx_metrics_user_id ON metrics(user_id);
CREATE INDEX idx_metrics_date ON metrics(date);
CREATE INDEX idx_chat_history_user_id ON chat_history(user_id);
CREATE INDEX idx_chat_history_created_at ON chat_history(created_at);

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;

-- Profiles policies
CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  USING (auth.uid() = user_id);

-- Plans policies
CREATE POLICY "Users can view own plans"
  ON plans FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own plans"
  ON plans FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own plans"
  ON plans FOR UPDATE
  USING (auth.uid() = user_id);

-- Workouts policies
CREATE POLICY "Users can view own workouts"
  ON workouts FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own workouts"
  ON workouts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own workouts"
  ON workouts FOR UPDATE
  USING (auth.uid() = user_id);

-- Metrics policies
CREATE POLICY "Users can view own metrics"
  ON metrics FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own metrics"
  ON metrics FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own metrics"
  ON metrics FOR UPDATE
  USING (auth.uid() = user_id);

-- Chat history policies
CREATE POLICY "Users can view own chat history"
  ON chat_history FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own chat history"
  ON chat_history FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- ============================================
-- FUNCTIONS
-- ============================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tables with updated_at
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_plans_updated_at
  BEFORE UPDATE ON plans
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_workouts_updated_at
  BEFORE UPDATE ON workouts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_metrics_updated_at
  BEFORE UPDATE ON metrics
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();
